# Generated by Django 2.1.2 on 2018-12-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='item_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='item_condition',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='your_name',
        ),
    ]
