# Generated by Django 2.1.2 on 2018-12-10 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20181209_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand',
            field=models.CharField(db_index=True, max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='condition',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='your_name',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
