# Generated by Django 2.1.2 on 2018-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20181211_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand',
            field=models.CharField(db_index=True, max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='condition',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(db_index=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='your_name',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
